# Global Configuration
# Change the directory where Jekyll will read files, or flag on the command-line (-s, --source DIR)
# Default is ./
#source: DIR

# Change the directory where Jekyll will write files, or flag on the command-line (-d, --destination DIR)
# Default is ./_site
#destination: DIR

# Where to find the pluguins
# Default is ./_plugins
#plugins: DIR

# Where to find the layouts files
# Default is ./_layouts
#layouts: DIR

# Where to find the data files
# Default is ./_data
#data_source: DIR

# Disable custom plugins, and ignore symbolic links
# Default is false
#safe: BOOL

# Exclude directories and/or files from the conversion.
# These exclusions are relative to the site's source directory and cannot be outside the source directory.
# Default is []
#exclude: [DIR, FILE, ...]
exclude: [_template, createCT.pl, .codio, .c9, .gitignore, newPost.pl, s3_website.yml]

# Force inclusion of directories and/or files in the conversion.
# Default is [".htaccess"]
#include [DIR, FILE, ...]

# When clobbering the site destination, keep the selected files. Useful for files that are not generated by jekyll;
# e.g. files or assets that are generated by your build tool. The paths are relative to the destination.
# Default is [".git", ".svn"]
#keep_files: [DIR, FIEL, ...]

# Set the time zone for site generation. This sets the TZ environment variable, which Ruby uses to handle time and date creation and manipulation.
# Any entry from the IANA Time Zone Database is valid, e.g. America/New_York. A list of all available values can be found http://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
# The default is the local time zone, as set by your operating system.
timezone: Asia/Chongqing

# Set the encoding of files by name. Only available for Ruby 1.9 or later).
# The default value is utf-8 starting in 2.0.0, and nil before 2.0.0, which will yield the Ruby default of ASCII-8BIT.
# Available encodings can be shown by the command ruby -e 'puts Encoding::list.join("\n")'.
# Default is "utf-8"
#encoding: "ENCODING"

# Serve Command Options (jekyll serve)
# Listen on the given port, or flag on command-line (--port PORT)
# Default is 4000
#port: PORT

# Listen at the given hostname, or flag command-line (--host HOSTNAME)
# Default is 0.0.0.0
#host: HOSTNAME

# Detach the server from the terminal, or flag command (-B, --detach)
# Default fasle
#detach: [BOOL]


# Site settings
title: 犹梦哲-主页
subtitle: 欢迎来到我的主页.
email: you.mengz@yahoo.com
author: "犹梦哲"
keywords: "犹梦哲,Mengz You"
description: > # this means to ignore newlines until "baseurl:"
  这里是犹梦哲的主页，进入我的博客，照片等入口。

copyright: "Copyright &copy;"

# Serve the website from the given base URL, or flag --baseurl URL on 'serve' sub-command.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mengz.me" # the base hostname & protocol for your site
twitter_username: mengzyou
github_username:  mengzyou
aboutme_username: mengz.you

# Filtering Content
# Show drafts or not
# Default is null
#show_drafts:

# Limit the number of posts to parse and publish, or flag on command-lin (--limit_posts NUM)
# Default is 0
#limit_posts: NUM

# Build Command Options (jekyll build)
# Publish posts with a future date, or flag on command-line (--future)
# Default is true
#future: BOOL

# Unpublished
# Default is false
#unpublished:

# Plugins
# Whitelis
# Default is []
#witelist:

# Gems
# Default is []
#gems:

# Build settings
# Conversion
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart

highlighter: pygments

# Produce an index for related posts, or flag on command-line (--lsi)
# Default is false
#lsi: BOOL

# Markdown file extension
# Default is "markdown,mkdown,mkdn,mkd,md"
#markdown_ext: ""

# Textile file extension
# Default is "textile"
#testile_ext: ""

# Below are default Configuration
#defaults: []

# Outputting
permalink: /blog/:year/:month/:day/:title.html
paginate: 10          # Posts per page on the blog index
paginate_path: "blog/page:num"  # Directory base for pagination URLs eg. /blog/page2/
excerpt_separator: "<!-- more -->"

category_dir: blog/categories/
tag_dir: blog/tags/

# Markdown Processors
#maruku:
#  use_tex:    false
#  use_divs:   false
#  png_engine: blahtex
#  png_dir:    images/latex
#  png_url:    /images/latex
#  fenced_code_blocks: true

#redcarpet:
#  extensions: []

#kramdown:
#  auto_ids:      true
#  footnote_nr:   1
#  entity_output: as_char
#  toc_levels:    1..6
#  smart_quotes:  lsquo,rsquo,ldquo,rdquo
#  use_coderay:   false

#coderay:
#  coderay_wrap:              div
#  coderay_line_numbers:      inline
#  coderay_line_number_start: 1
#  coderay_tab_width:         4
#  coderay_bold_every:        10
#  coderay_css:               style

#redcloth:
#  hard_breaks: true

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: mengzyou
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: mengzyou
twitter_tweet_button:
twitter_timeline:

# Google +1
google_plus_one:
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: mengz.you@gmail.com
googleplus_hidden: false

# Disqus Comments
disqus_short_name: youmz
disqus_show_comment_count: ture

# Duoshuo Comments
duoshuo_short_name: blogmengzme

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like:

# Addthis button
addthis_button:

# Jiathis button
jiathis_button: true
